sudo: false

services:
  - docker

before_script:
  - docker -v
  - docker build . -t $APP_IMAGE -t $APP_IMAGE:dev

script:
  - docker run --rm -e TTD_USERNAME -e TTD_PASSWORD -e TTD_ADGROUP_TEMPLATES_CAMPAIGN_ID $APP_IMAGE python -m pytest

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true

branches:
  only:
    - master
    - /\d+\.\d+\.\d+/
